title: "Predicting Vancouver's Airbnb Price"
author: "Bill Wan"
date: "2024-01-05"
sphinx:
  config:
    bibtex_reference_style: author_year
execute:
  execute_notebooks: force 
bibtex_bibfiles:
  - references.bib
html_theme_options:
  # Commented out footer_info and copyright
  #footer_info: "Custom footer text goes here. Omit or customize as needed."
  #copyright: "Copyright © 2023 by the authors. All rights reserved."
  show_sidebar: false
  logo: false
  logo_name: false
html_css_files:
  - 'custom.css'
